-- Generated by Awesome Menu Generator
-- Based on LXMED http://lxmed.sourceforge.net/ project
module("applicationsmenu")

applicationsmenu = {}

applicationsmenu[10] = {
{[====[Open a New Window]====], [====[terminator]====]},
{[====[Sakura]====], [====[sakura]====]}
}
applicationsmenu[20] = {
{[====[Avogadro]====], [====[avogadro %f]====]}
}
applicationsmenu[30] = {
}
applicationsmenu[40] = {
}
applicationsmenu[50] = {
{[====[Avahi SSH Server Browser]====], [====[/usr/bin/bssh]====]},
{[====[Avahi VNC Server Browser]====], [====[/usr/bin/bvnc]====]},
{[====[Chromium]====], [====[chromium]====]},
{[====[Firefox]====], [====[firefox %u]====]},
{[====[Wicd]====], [====[/usr/bin/wicd-client]====]}
}
applicationsmenu[60] = {
{[====[LibreOffice]====], [====[libreoffice]====]},
{[====[LibreOffice Base]====], [====[libreoffice --base]====]},
{[====[LibreOffice Calc]====], [====[libreoffice --calc]====]},
{[====[LibreOffice Draw]====], [====[libreoffice --draw]====]},
{[====[LibreOffice Impress]====], [====[libreoffice --impress]====]},
{[====[LibreOffice Math]====], [====[libreoffice --math]====]},
{[====[LibreOffice Writer]====], [====[libreoffice --writer]====]}
}
applicationsmenu[70] = {
{[====[Network]====], [====[nm-applet]====]}
}
applicationsmenu[80] = {
{[====[CMake]====], [====[cmake-gui %f]====]},
{[====[NetBeans IDE 6.9.1]====], [====[/bin/sh "/home/hderms/netbeans-6.9.1/bin/netbeans"]====]},
{[====[OpenJDK Monitoring & Management Console]====], [====[/usr/bin/jconsole]====]},
{[====[OpenJDK Policy Tool]====], [====[/usr/bin/policytool]====]},
{[====[Qt Assistant]====], [====[/usr/bin/assistant]====]},
{[====[Qt Designer]====], [====[/usr/bin/designer]====]},
{[====[Qt Linguist]====], [====[/usr/bin/linguist]====]}
}
applicationsmenu[90] = {
{[====[MPlayer Media Player]====], [====[mplayer %F]====]},
{[====[QT V4L2 test Utility]====], [====[qv4l2]====]},
{[====[VLC media player]====], [====[/usr/bin/vlc]====]}
}
applicationsmenu[100] = {
{[====[Avahi Zeroconf Browser]====], [====[/usr/bin/avahi-discover]====]},
{[====[dconf Editor]====], [====[dconf-editor]====]},
{[====[Htop]====], [====[htop]====]},
{[====[Manage Printing]====], [====[/usr/bin/xdg-open http://localhost:631/]====]}
}
applicationsmenu[110] = {
{[====[Adobe Flash Player]====], [====[flash-player-properties]====]},
{[====[Bluetooth Manager]====], [====[blueman-manager]====]},
{[====[Network Connections]====], [====[nm-connection-editor]====]},
{[====[Qt Config]====], [====[/usr/bin/qtconfig]====]}
}

applicationsmenu[1] = {
{[====[Accessories]====], applicationsmenu[10]},
{[====[Education]====], applicationsmenu[20]},
{[====[Games]====], applicationsmenu[30]},
{[====[Graphics]====], applicationsmenu[40]},
{[====[Internet]====], applicationsmenu[50]},
{[====[Office]====], applicationsmenu[60]},
{[====[Other]====], applicationsmenu[70]},
{[====[Programming]====], applicationsmenu[80]},
{[====[Sound & Video]====], applicationsmenu[90]},
{[====[System Tools]====], applicationsmenu[100]},
{[====[Preferences]====], applicationsmenu[110]}
}

passed = applicationsmenu[1]
function applicationsmenu() return passed end